import Fastify from 'fastify';
import cors from '@fastify/cors'; 
import jwt from '@fastify/jwt'; 
import argon2 from 'argon2'; 
import pg from 'pg'; 
import {z} from 'zod';
const {Pool}=pg; const pool=new Pool({connectionString:process.env.DATABASE_URL||'postgresql://financeiro:financeiro@localhost:5432/financeiro'});
const app=Fastify({logger:true}); app.register(cors,{origin:true}); app.register(jwt,{secret:process.env.JWT_SECRET||'dev-secret-change-me'});
const q=async(text:string,values:any[]=[])=>pool.query(text,values);
app.get('/health',async()=>({ok:true}));
app.post('/auth/register',async(req,rep)=>{const b=z.object({name:z.string().min(2),email:z.string().email(),password:z.string().min(6)}).parse(req.body); const hash=await argon2.hash(b.password); try{const r=await q('insert into users(name,email,password_hash) values($1,$2,$3) returning id,name,email,currency,timezone',[b.name,b.email,hash]); const token=app.jwt.sign({sub:r.rows[0].id}); return {user:r.rows[0],token}}catch(e){return rep.code(409).send({error:'E-mail já cadastrado'})}});
app.post('/auth/login',async(req,rep)=>{const b=z.object({email:z.string().email(),password:z.string()}).parse(req.body); const r=await q('select * from users where email=$1',[b.email]); if(!r.rowCount||!(await argon2.verify(r.rows[0].password_hash,b.password))) return rep.code(401).send({error:'Credenciais inválidas'}); const u=r.rows[0]; return {user:{id:u.id,name:u.name,email:u.email,currency:u.currency,timezone:u.timezone},token:app.jwt.sign({sub:u.id})}});
app.decorate('auth',async(req:any,rep:any)=>{try{await req.jwtVerify()}catch{return rep.code(401).send({error:'Não autenticado'})}});
const uid=(req:any)=>req.user.sub;
app.get('/accounts',{preHandler:(app as any).auth},async(req:any)=> (await q('select * from accounts where user_id=$1 and archived_at is null order by name',[uid(req)])).rows);
app.post('/accounts',{preHandler:(app as any).auth},async(req:any)=>{const b=z.object({name:z.string(),type:z.enum(['corrente','poupanca','carteira','investimento','cartao_credito']),initial_balance:z.number().default(0),color:z.string().optional(),icon:z.string().optional()}).parse(req.body); const r=await q('insert into accounts(user_id,name,type,initial_balance,current_balance,color,icon) values($1,$2,$3,$4,$4,$5,$6) returning *',[uid(req),b.name,b.type,b.initial_balance,b.color,b.icon]); return r.rows[0]});
app.get('/categories',{preHandler:(app as any).auth},async(req:any)=> (await q('select * from categories where user_id is null or user_id=$1 order by type,name',[uid(req)])).rows);
app.post('/categories',{preHandler:(app as any).auth},async(req:any)=>{const b=z.object({name:z.string(),type:z.enum(['receita','despesa']),parent_id:z.string().uuid().nullable().optional()}).parse(req.body); return (await q('insert into categories(user_id,name,type,parent_id) values($1,$2,$3,$4) returning *',[uid(req),b.name,b.type,b.parent_id||null])).rows[0]});
app.get('/transactions',{preHandler:(app as any).auth},async(req:any)=>{const r=await q(`select t.*,a.name account_name,c.name category_name from transactions t join accounts a on a.id=t.account_id left join categories c on c.id=t.category_id where t.user_id=$1 order by t.date desc,t.id desc limit 100`,[uid(req)]); return r.rows});
app.post('/transactions',{preHandler:(app as any).auth},async(req:any,rep:any)=>{const b=z.object({account_id:z.string().uuid(),category_id:z.string().uuid().nullable().optional(),type:z.enum(['receita','despesa','transferencia']),amount:z.number().positive(),description:z.string().min(1),notes:z.string().optional(),date:z.string(),status:z.enum(['pendente','confirmado']).default('confirmado')}).parse(req.body); const client=await pool.connect(); try{await client.query('begin'); const r=await client.query('insert into transactions(user_id,account_id,category_id,type,amount,description,notes,date,status) values($1,$2,$3,$4,$5,$6,$7,$8,$9) returning *',[uid(req),b.account_id,b.category_id||null,b.type,b.amount,b.description,b.notes||null,b.date,b.status]); const delta=b.type==='receita'?b.amount:-b.amount; if(b.status==='confirmado') await client.query('update accounts set current_balance=current_balance+$1 where id=$2 and user_id=$3',[delta,b.account_id,uid(req)]); await client.query('commit'); return r.rows[0]}catch(e){await client.query('rollback'); return rep.code(400).send({error:'Não foi possível criar lançamento'})}finally{client.release()}});
app.get('/dashboard',{preHandler:(app as any).auth},async(req:any)=>{const id=uid(req); const [a,m,t]=await Promise.all([q('select coalesce(sum(current_balance),0) total from accounts where user_id=$1 and archived_at is null',[id]),q(`select coalesce(sum(case when type='receita' then amount else 0 end),0) receitas,coalesce(sum(case when type='despesa' then amount else 0 end),0) despesas from transactions where user_id=$1 and date>=date_trunc('month',current_date) and date<date_trunc('month',current_date)+interval '1 month'`,[id]),q('select t.*,a.name account_name,c.name category_name from transactions t join accounts a on a.id=t.account_id left join categories c on c.id=t.category_id where t.user_id=$1 order by t.date desc,t.id desc limit 5',[id])]); return {saldo_total:Number(a.rows[0].total),receitas_mes:Number(m.rows[0].receitas),despesas_mes:Number(m.rows[0].despesas),ultimos:t.rows}});
app.get('/budgets',{preHandler:(app as any).auth},async(req:any)=> (await q(`select b.*,c.name category_name from budgets b join categories c on c.id=b.category_id where b.user_id=$1 order by year desc,month desc`,[uid(req)])).rows);
app.get('/goals',{preHandler:(app as any).auth},async(req:any)=> (await q('select * from goals where user_id=$1 order by target_date nulls last',[uid(req)])).rows);
app.get('/recurring',{preHandler:(app as any).auth},async(req:any)=> (await q('select r.*,a.name account_name,c.name category_name from recurring_rules r join accounts a on a.id=r.account_id left join categories c on c.id=r.category_id where r.user_id=$1 order by next_run_date',[uid(req)])).rows);
app.get('/reports',{preHandler:(app as any).auth},async(req:any)=>{const id=uid(req); return (await q(`select c.name category_name,sum(t.amount)::numeric amount from transactions t left join categories c on c.id=t.category_id where t.user_id=$1 and t.type='despesa' and t.date>=date_trunc('month',current_date) group by c.name order by amount desc`,[id])).rows});
app.listen({port:Number(process.env.PORT||3333),host:'0.0.0.0'}).catch(console.error);



